### ISSUE TITLE
Support node8 ?

### ISSUE THREAD

**Issue by JBustin** [florianheinemann/passwordless-redisstore#11]
#10 Hi,

I try my application with node8 (from v6.11.1 to v8.9.0).
When i require the module `const RedisStore = require('passwordless-redisstore')`, i've got this error :

```
Error: Module version mismatch. Expected 48, got 57.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at bindings (/Users/me/myWorkspace/myOrga/myApp/node_modules/bindings/bindings.js:76:44)
   at Object.<anonymous> (/Users/me/myWorkspace/myOrga/myApp/node_modules/bcrypt/bcrypt.js:3:35)
...
```

It seems that node v8.9.0 (LTS) is not supported by bcrypt.

Maybe, this : https://github.com/kelektiv/node.bcrypt.js/issues/513

Should it be better to use `bcryptjs` to avoid this kind of issue ? https://github.com/dcodeIO/bcrypt.js

Thks

**Comment by JBustin** [comment]
I just find : https://github.com/lloydcotten/passwordless-redisstore

**Comment by recrsn** [comment]
@JBustin. If you update node, you must recompile your native addons. NodeJS v8+ are fully supported by bcrypt.

````
npm rebuild bcrypt
````
This should do the task.

**Comment by JBustin** [comment]
@agathver it was a problem with pm2 + yarn + nvm, and a curious manage of natives libraries.
Totally clean of pm2 resolves the problem.
Thks
